### PR TITLE
Create alt3DParts

### PR DESCRIPTION
**Pull request by zogtrog**
These files are to create 3D printed parts for the fabscan when alternative hardware components have been used during assembly.

### CODE REVIEW

**Comment by zogtrog** [comment]
back_to_front_fabscan
fab_scan_alt_laser_holder
turn_table_mount

**Comment by zogtrog** [comment]
[altparts3D.zip](https://github.com/mariolukas/FabScanPi-Server/files/276328/altparts3D.zip)

**Comment by zogtrog** [comment]
Struggling with git. Think I managed to upload the files

**Comment by mariolukas** [comment]
Thanks for the pull request, but this is the repository for the Server application. There is another repository for all the case related stuff. Please do a pull request on this repository. https://github.com/mariolukas/FabScan-Case

**Comment by zogtrog** [comment]
Sorry I will try to post it there instead.

**Pull request closed without merging**
